Mkdir $buid_dir/bin before copying bin/start-nginx into it

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -6,7 +6,7 @@ status() {
 }
 
 set -e            # fail fast
-set -o pipefail   # don't ignore exit codes when piping output
+set -o pipefail   # dont ignore exit codes when piping output
 
 NGINX_VERSION=1.5.7
 PCRE_VERSION=8.21
@@ -34,13 +34,22 @@ status "Compiling nginx"
 status "Installing nginx"
 make install --silent
 
-# Copy the installation where it'll persist
-mv /app/nginx $build_dir/nginx
-
-# bin/stat-nginx
+mkdir -p "$build_dir/bin/"
+cp "/app/nginx" "$build_dir/bin/nginx"
+nginx_version=$(./bin/nginx-$STACK -V 2>&1 | head -1 | awk '{ print $NF }')
+status "nginx-buildpack: Installed ${NGINX_VERSION} to app/bin"
 cp bin/start-nginx "$build_dir/bin/"
-status "Added start-nginx to app/bin"
+status "nginx-buildpack: Added start-nginx to app/bin"
 
-# Add to PATH
-mkdir -p $build_dir/.profile.d
-echo 'PATH=$PATH:$HOME/nginx/sbin' > $build_dir/.profile.d/nginx_path.sh
+mkdir -p "$build_dir/config"
+
+cp config/mime.types "$build_dir/config/"
+status "nginx-buildpack: Default mime.types copied to app/config/"
+
+if [[ ! -f $build_dir/config/nginx.conf.erb ]]; then
+	cp config/nginx.conf.erb "$build_dir/config/"
+	status "nginx-buildpack: Default config copied to app/config."
+else
+	status "nginx-buildpack: Custom config found in app/config."
+fi
+exit 0
